export const cardData = [
  {
    id:1,
    category: "WHAT'S NEW",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 5,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:2,
    category: "PRODUCTIVITY",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 3,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:3,
    category: "WHAT'S NEW",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 7,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:4,
    category: "SALE'S",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 9,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:5,
    category: "WHAT'S NEW",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 2,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:6,
    category: "PRODUCTIVITY",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 8,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:7,
    category: "PRODUCTIVITY",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 5,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:8,
    category: "WHAT'S NEW",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 4,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:9,
    category: "PRODUCTIVITY",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 3,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:10,
    category: "WHAT'S NEW",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 5,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:11,
    category: "WHAT'S NEW",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 4,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:12,
    category: "PRODUCTIVITY",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 3,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:13,
    category: "WHAT'S NEW",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 5,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:14,
    category: "WHAT'S NEW",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 4,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
  {
    id:15,
    category: "PRODUCTIVITY",
    text: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
    readTime: 3,
    description: `Ut irure dolor deserunt cillum reprehenderit anim aliqua dolor nostrud commodo.`,
  },
];
